# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Inject environment variables for database configuration
      DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}  # Database URL
      DEV_DATABASE_USERNAME: ${{ secrets.DEV_DATABASE_USERNAME }}  # Database username
      DEV_DATABASE_PASSWORD: ${{ secrets.DEV_DATABASE_PASSWORD }}  # Database password
      SPRING_PROFILES_ACTIVE: ci  # Specify the Spring profile for CI (use 'ci' profile)
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DEV_DATABASE_PASSWORD }}
          MYSQL_DATABASE: touristguide
        ports:
          - 3306:3306  # Expose MySQL on port 3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Print environment variables (debugging)
        run: |
          echo "DEV_DATABASE_URL=$DEV_DATABASE_URL"
          echo "DEV_DATABASE_USERNAME=$DEV_DATABASE_USERNAME"
          echo "DEV_DATABASE_PASSWORD=$DEV_DATABASE_PASSWORD"
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  qodana:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_775288666 }}
